name: Setup Build Test Publish
on: 
  - push
  - pull_request
jobs:
  setup_build_test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java_version: [11, 17]
        node_version: [16.x, 18.x]
        java_dist: [ 'temurin', 'microsoft' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_dist }}
          java-version: ${{ matrix.java_version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Setup & Run Tests
        run: |
          npm version
          npm install
          npm test
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Publish
        run: npm publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
